spring:
  application:
    name: gateway-service

server:
  port: 8080

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    server:
      waitTimeInMsWhenSyncEmpty: 0
    serviceUrl:
      defaultZone: http://localhost:8302/eureka/

zuul:
  # services will be mapped under the /api prefix
  prefix: /api
  routes:
    watchlist:
      path: /**
      serviceId: watchlist-service
    stock-quote:
      path: /**
      serviceId: stock-quote-service
